/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/auth/AuthForm.vue')['default']
    ButtonTool: typeof import('./src/components/paint/ButtonTool.vue')['default']
    Canvas: typeof import('./src/components/paint/Canvas.vue')['default']
    Chat: typeof import('./src/components/chat/Chat.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ModalAuth: typeof import('./src/components/modal/ModalAuth.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    PaintBlock: typeof import('./src/components/paint/PaintBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBar: typeof import('./src/components/paint/ToolBar.vue')['default']
  }
}
